### ISSUE TITLE
Forward Slash in Import breaks script on Windows

### ISSUE THREAD

**Issue by AbeFM** [Ghostkeeper/SlicerTestModels#1]
I inserted/edited the following lines into the script:
```
import("C:/Users/Abe/Google Drive/3D_Printing/Objects/~AbeStuff/BioMolecules/DEVELOPMENT/Protien and Crops/SmallerSupportRemovalTest.3mf");

max_height = 1000; //Some very big number, higher than the maximum height of the model.
your_model = "SmallerSupportRemovalTest.3mf"; //The model you're generating support for.

```

And got the following output at runtime:
```
Loaded design 'C:/Users/Abe/Google Drive/3D_Printing/generate_support_model_only.scad'.
Compiling design (CSG Tree generation)...
Compiling design (CSG Products generation)...
WARNING: Can't open import file 'C:/Users/Abe/Google Drive/3D_Printing\your_model.stl', import() at line 8
Geometries in cache: 6
```

Note the next to last line is an error:
WARNING: Can't open import file 'C:/Users/Abe/Google Drive/3D_Printing ** \ ** your_model.stl', import() at line 8
I believe the backslash in the path is causing the failure. This wouldn't be obvious under *nix, but breaks in Windows.

**Comment by Ghostkeeper** [comment]
According to the OpenSCAD documentation, backslashes must be escaped in file paths: https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/STL_Import_and_Export#import
This is a feature of the OpenSCAD language: The backslash is the escape character so it's looking for the escape character `\y` which doesn't exist and then becomes just `y`. So it'd look for the file `C:/Users/Abe/Google Drive/3D_Printingyour_model.stl` which doesn't exist.

There is nothing that this script can really do about it, so I'll close the issue. Sorry! You've been having a lot of trouble with that model...

A fix would be to escape the backslash, like this: `C:/Users/Abe/Google Drive/3D_Printing\\your_model.stl`

**Comment by AbeFM** [comment]
I think it would be to escape the FORWARD slash.
```
your_model = "C:/Users/Abe/Google Drive/3D_Printing/Objects/~AbeStuff/BioMolecules/DEVELOPMENT/Protien and Crops//SupportRemovalTest.stl"; //The model you're generating support for.
```

Similarly, the routine works if you directly paste the entire path in each instance - without the escaped forward slash.

It leads me to believe it is something in the interpretation on the backend. This worked:
```
minkowski() {
import("C:/Users/Abe/Google Drive/3D_Printing/Objects/~AbeStuff/BioMolecules/DEVELOPMENT/Protien and Crops/SupportRemovalTest.stl");
translate([0, 0, -max_height]) {
```

Probably not worth fixing, I would change the comment on that line to:

```
//The model you're generating support for.
//In Windows, use a double forward slash between path and filename: " C:/<mypath>//<myfile.stl> "
```
